name: icons_plus_slim
description: Icons Plus is a package that has only a few icon packs that are popular and easy to use
version: 5.0.0
homepage: https://github.com/tapvt/icons_plus_slim
repository: https://github.com/tapvt/icons_plus_slim
issue_tracker: https://github.com/tapvt/icons_plus_slim

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

screenshots:
  - description: 'Icons Plus Banner'
    path: icons-plus.svg

flutter:
  # Images
  assets:
    # Popular SVG images
    - assets/images/popular/common-actions/
    - assets/images/popular/documents-and-folders/
    - assets/images/popular/other/
    - assets/images/popular/settings/
    - assets/images/popular/social-media/
    - assets/images/popular/status/
    - assets/images/popular/website-sections/

  # Fonts
  fonts:
    # EvaIcons
    - family: EvaIcons
      fonts:
        - asset: assets/fonts/EvaIcons.ttf
    # FontAwesome
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    # TeenyIcons
    - family: TeenyIcons
      fonts:
        - asset: assets/fonts/TeenyIcons.ttf
